### ISSUE TITLE
Compta - Rapprochement bancaire - numéro 

### ISSUE THREAD

**Issue by elodiegeoffroy** [ArnaudDLT/assoconnect-dev#122]
demandé par MGEN : ajouter le numéro du chèque

**Comment by elodiegeoffroy** [comment]
@bertrandflaujac je réitère ma demande et je t'assigne donc :)  Il y a souvent les écritures d'un même montant et donc difficiles à différencier.

**Comment by PierreGrateau** [comment]
@bertrandflaujac demandé par Biomnis aussi

**Comment by bertrandflaujac** [comment]
@elodiegeoffroy @PierreGrateau sera pris en compte dans la version qui arrive
