### ISSUE TITLE
Envoyer un message automatique pour les comptes trials qui ont expirés

### ISSUE THREAD

**Issue by bertrandflaujac** [ArnaudDLT/assoconnect-dev#146]
Pour les personnes qui ont souhaité essyer AssoConnect pdt 15/30 jours, mais dont le compte d'essai a expiré, ça serait bien si on pouvait leur envoyer un mail leur permettant d'etendre leur période d'essai à plusieurs jours s'ils n'ont pas eu le temps de d'essayer à fond notre service. 

Utile pour ne pas perdre des prospect
![capture](https://cloud.githubusercontent.com/assets/6660114/5837440/9a525764-a17f-11e4-8a1a-ab35c24de518.JPG)

**Comment by sylfabre** [comment]
@bertrandflaujac Noté dans Trello
