### ISSUE TITLE
Bloc "lien"

### ISSUE THREAD

**Issue by ArnaudDLT** [ArnaudDLT/assoconnect-dev#151]
Ajouter un bloc "lien" dans le DIY afin de rajouter un lien type "En savoir plus"

**Comment by sylfabre** [comment]
@ArnaudDLT Qui ouvrirait une lightbox ?

**Comment by ArnaudDLT** [comment]
@sylfabre non, qui redirigerait vers une autre page.
- Soit une page du site
- Soit d'un autre site

On peut le faire aujourd'hui, mais pas simple pour un papy :)
