### ISSUE TITLE
Classez les groupes par ordre alphabétique

### ISSUE THREAD

**Issue by PierreGrateau** [ArnaudDLT/assoconnect-dev#161]
https://www.judo-aquitaine.com/ammj/plateforme/organisations/2951
Demandé par un club de judo

**Comment by sylfabre** [comment]
Fait

**Comment by PierreGrateau** [comment]
@sylfabre sur cette page aussi stp : https://www.judo-aquitaine.com/ammj/admin/liste

**Comment by sylfabre** [comment]
@PierreGrateau Fait sur la beta
