### ISSUE TITLE
Page d'accès à l'admin

### ISSUE THREAD

**Issue by PierreGrateau** [ArnaudDLT/assoconnect-dev#167]
https://www.judo-aquitaine.com/ussp-amikuze-judo/membres/plateforme/2225
Il faut conserver les groupes par ordre alphabétique 
mais renommer le compte principal en "Administration principale - (nom de l'asso)" comme ça elle remonte au moins sur la 1ère ligne

**Comment by sylfabre** [comment]
Fait
