### ISSUE TITLE
Accès donné au responsable ligue à la plateforme

### ISSUE THREAD

**Issue by PierreGrateau** [ArnaudDLT/assoconnect-dev#168]
Il faudrait que les clubs puissent activer ou désactiver l'accès de Benoit à leurs plateformes. 
A priori c'est une condition sinequanon pour plusieurs clubs. Je pense qu'il faudrait que le bouton on/off soit là : https://www.judo-aquitaine.com/demo/plateforme/configuration/3106

@sylfabre @ArnaudDLT Il faudrait que ce soit develloppé avant samedi 28 mars : journée de formation dans les Landes où il y aura Saïd et le potentiel prochain président Pierre Abadi qui est directeur du comité des Landes

**Comment by sylfabre** [comment]
@PierreGrateau https://trello.com/c/W7Pljadl/674-acces-acces-du-compte-admin-site-aux-plateformes
