### ISSUE TITLE
Enveloppe avec subventions calculées de manière différente

### ISSUE THREAD

**Issue by PierreGrateau** [ArnaudDLT/assoconnect-dev#199]
Demandé plusieurs fois, souvent par des gros CE
@ArnaudDLT LexisNexis ntmt mais aussi Aloes par exemple ou Nexeya

**Comment by sylfabre** [comment]
@PierreGrateau peux-tu détailler stp ?
Quelles méthodes de calcul devraient être disponibles ?

**Comment by PierreGrateau** [comment]
@sylfabre 
Ex : 200€ d'enveloppe pour la culture
Remboursement de 3€ pour les billets de musée
Remboursement de 50% avec plafond de 20€ pour les billets de spectacle

**Comment by bertrandflaujac** [comment]
@PierreGrateau on ferme. C'est géré avec l'évolution de a subvention
