### ISSUE TITLE
Espace membre

### ISSUE THREAD

**Issue by PierreGrateau** [ArnaudDLT/assoconnect-dev#204]
https://www.assoconnect.com/demo-type-culture/site/menus/9495
Si un menu n'est accessible qu'aux utilisateurs connectés, on a aujourd'hui une option: rendre la page visible mais lui refuser l'accès. 
Je pense qu'il faudrait mieux dans ce cas rediriger vers la page de connexion. 
Ce serait plus pertinent notamment pour un menu de type "Espace membre"

**Comment by sylfabre** [comment]
@PierreGrateau Doublon #206
