### ISSUE TITLE
Remboursement sur reçu - enregistrement des coordonnées bancaires

### ISSUE THREAD

**Issue by PierreGrateau** [ArnaudDLT/assoconnect-dev#210]
La première fois qu'une personne enregistre ses coordonnées bancaires, elle est redirigée vers son profil.
Il faudrait que ce soit le cas mais que uniquement les infos bancaires soient visibles car actuellement ça prete à confusion, la personne a l'impression qu'elle doit remettre son mot de passe etc..

**Comment by sylfabre** [comment]
Il suffirait de le faire directement dans la bonne page !

**Comment by bertrandflaujac** [comment]
@PierreGrateau va être traité dans le petit sujet du jour je ferme
