### ISSUE TITLE
DIY - Crop photos

### ISSUE THREAD

**Issue by ArnaudDLT** [ArnaudDLT/assoconnect-dev#218]
Pouvoir les couper => évite de devoir le faire sur psd + utile pour ceux qui ne savent pas faire

**Comment by sylfabre** [comment]
@ArnaudDLT Dans un bloc image ? La fonction de déplacement dans le cadre ne suffit pas ?

**Comment by ArnaudDLT** [comment]
@sylfabre je ne me souviens plus quel était l'usage :(
