### ISSUE TITLE
DIY - message sauvegarder travaille avant quitter une page

### ISSUE THREAD

**Issue by bertrandflaujac** [ArnaudDLT/assoconnect-dev#219]
Si on quitte une page d'édition sans avoir sauvegardé son travail, on perd tout le contenu. 
Il faudrait avoir une lightbox avec message "Voulez vous  enregistrer les modifications apportées à votre page avant de quitter ? Oui / Non / annuler" avant de quitter la page.

**Comment by sylfabre** [comment]
@bertrandflaujac C'est fait pour le DIY. Il faut noter en bug là où ça ne l'ait pas
