### ISSUE TITLE
Propriétés utilisateurs et groupe

### ISSUE THREAD

**Issue by sylfabre** [ArnaudDLT/assoconnect-dev#232]
Permettre à un groupe d'avoir sa propre liste de propriétés utilisateur qu'un utilisateur peut renseigner qu'à condition d'être membre du groupe.
Utile pour un club omnisport par exemple où chaque groupe correspond à un sport.

@PierreGrateau pour info

**Comment by bertrandflaujac** [comment]
@sylfabre intégré dans le CDC Groupe
