### ISSUE TITLE
Gestion des factures

### ISSUE THREAD

**Issue by sarahbouyou** [ArnaudDLT/assoconnect-dev#241]
Bonjour Sylvain!

Lorsque j'essaie de payer des factures, aucun message d'erreur ne s'affiche, pourtant les factures restent affichées, autrement dit elles n'ont pas été payées

https://www.plateforme-ce.com/demo/master/factures

![image](https://cloud.githubusercontent.com/assets/12234283/7470408/1ac87952-f31d-11e4-8414-adcc2a1b5f88.png)

Merci pour ton aide!

**Comment by sylfabre** [comment]
@sarahbouyou Attention ici c'est la boîte à idée, pas les bugs !
Quelle facture en particulier pose problème ?

**Comment by sarahbouyou** [comment]
@sylfabre ah oui désolée !
Ça ne concerne pas une facture en particulier, je n'arrive à en payer aucune..
Peut-être que leur dossier n'est pas complet, mais aucun message n'apparaît spécifiant le manque d'une pièce dans leur dossier

**Comment by sylfabre** [comment]
@sarahbouyou Je viens de rajouter le statut du wallet dans le listing pour être capable de mieux savoir ce qui est payable. Est-ce que le problème se produit encore avec les associations dont le wallet est vérifié ?

**Comment by sarahbouyou** [comment]
@sylfabre on voit que les wallets sont vérifiés, mais on ne peut toujours pas les payer

**Comment by sylfabre** [comment]
@sarahbouyou On continue la discussion sur le bug que tu as noté
