### ISSUE TITLE
Galerie Photos - Ajout groupé de photos 

### ISSUE THREAD

**Issue by elodiegeoffroy** [ArnaudDLT/assoconnect-dev#25]
Je ne sais pas si cela a été évoqué mais serait-il possible que le CE puisse ajouter plusieurs photos à la fois? Certains CE ont beaucoup de photos et c'est un peu long de les télécharger une par une

**Comment by bertrandflaujac** [comment]
@elodiegeoffroy devrait être pris en compte dans le prochain CDC Galerie à venir
