### ISSUE TITLE
Calendrier - bloquer la saisie manuelle des dates 

### ISSUE THREAD

**Issue by elodiegeoffroy** [ArnaudDLT/assoconnect-dev#345]
@bertrandflaujac On peut saisir manuellement la date au lieu de la sélectionner grâce au calendrier mais cela n'est pas pris en compte et on n'est pas prévenu. Un CE a fait sa compta en saisissant manuellement les dates et viennent de se rendre compte que les bonnes dates n'ont pas été enregistrées. Il faudrait que ce la saisie manuelle soit bloquée

**Comment by sylfabre** [comment]
@elodiegeoffroy C'est un bug, pas une amélioration !
https://github.com/sylfabre/buypacker-dev/issues/5823

**Comment by elodiegeoffroy** [comment]
@sylfabre Ok autant pour moi :)
