### ISSUE TITLE
articles uniques fil d'actualité

### ISSUE THREAD

**Issue by hadrienmazery** [ArnaudDLT/assoconnect-dev#52]
Il faudrait avoir la possibilité de choisir si les articles ajouté dans "actualité" coté admin et qui apparaissent dans "fil d'actualité" coté public sont visibles en entier ou juste en aperçu avec un bouton voir plus .
Cas de daltys qui n'a qu'un article et voudrait pouvoir le voir en entier directement.

**Comment by bertrandflaujac** [comment]
Va être pris en compte dans les pistes d'amliorations de article
