### ISSUE TITLE
Onglet "Toutes les offres" - ajouter une couleur ou revoir l'organisation

### ISSUE THREAD

**Issue by elodiegeoffroy** [ArnaudDLT/assoconnect-dev#87]
@ArnaudDLT Linkeo a fait tester le site à 12 personnes, sur les 12, aucune n'a eu l'idée de cliquer sur l'onglet "toutes les offres" qui est, selon eux, pas assez mis en avant. Pourrait-on le mettre en couleur ? Autre proposition : lorsqu'on clique sur le menu "offres: avoir uniquement le titres des deux catalogues qui s'affiche. Si l'on clique sur "sélection d'offres", on voit les offres qui s'affichent et si l'on clique sur "toutes les offres" on voit la catalogue tickenet qui s'ouvre dans une autre page.

**Comment by bertrandflaujac** [comment]
Evolution effectuée
